### ISSUE TITLE
Tile boxes alignment on https://myhomesolutions.ai/contact-us/

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/myhomesolutions.ai#3]
@codextiny Can you please tell me how to properly align this tile boxes? 
<img width="1292" alt="image" src="https://github.com/shannonbaldwin/myhomesolutions.ai/assets/167017886/c67add1f-98c7-43fc-8708-fd537d42823a">

**Comment by codextiny** [comment]
@shannonbaldwin 

fixed, please check
